# Project
version=6.0.0
group=dev.boxadactle
java_version=21

# Common
minecraft_version=1.21.8
mod_name=BoxHud
mod_author=Boxadactle
mod_id=boxhud
license=GPLv3
credits=
description=BoxHud is a Minecraft mod that adds a suite of powerful and customizable PvP-style HUD widgets, with a focus on performance and customizability.
minecraft_version_range=[1.21.5, 1.22)
minecraft_version_range_fabric=>=1.21.5
enabled_platforms=neoforge,fabric,forge

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric https://fabricmc.net/develop/
fabric_version=0.131.0+1.21.8
fabric_loader_version=0.17.2

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=58.0.5
forge_loader_version_range=[56,)

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.31
neoforge_loader_version_range=[2,)

# BoxLib https://modrinth.com/mod/boxlib#download
boxlib_version=18.0.3
boxlib_version_range=[18,19)
boxlib_version_range_fabric=18.x

# Coordinates Display
coordinates_display_version = 17.0.2
coordinates_display_version_range=[17.0, 18.0)
coordinates_display_version_range_fabric=17.x

# modmenu https://modrinth.com/mod/modmenu
modmenu_version=15.0.0-beta.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# publishing
game_versions = 1.21.6,1.21.7,1.21.8
project_id_curseforge = 1320027
project_id_modrinth = gjFWUARA
release_type = release
changelog_file = CHANGELOG.md