# Project
version=4.0.1
group=dev.boxadactle
java_version=21

# Common
minecraft_version=1.21.4
mod_name=BoxHud
mod_author=Boxadactle
mod_id=boxhud
license=GPLv3
credits=
description=BoxHud is a Minecraft mod that adds a suite of powerful and customizable PvP-style HUD widgets, with a focus on performance and customizability.
minecraft_version_range=[1.21.4, 1.22)
minecraft_version_range_fabric=>=1.21.4
enabled_platforms=neoforge,fabric,forge

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric https://fabricmc.net/develop/
fabric_version=0.119.3+1.21.4
fabric_loader_version=0.16.14

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=54.1.6
forge_loader_version_range=[54,)

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.4.149
neoforge_loader_version_range=[2,)

# BoxLib https://modrinth.com/mod/boxlib#download
boxlib_version=16.0.2
boxlib_version_range=[16,18)
boxlib_version_range_fabric=16.x

# Coordinates Display
coordinates_display_version = 15.0.0-snapshot
coordinates_display_version_range=[15.0, 16.0)
coordinates_display_version_range_fabric=15.x

modmenu_version=13.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# publishing
game_versions = 1.21.4
project_id_curseforge = 1320027
project_id_modrinth = gjFWUARA
release_type = release
changelog_file = CHANGELOG.md