# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=9.0.0
group=dev.boxadactle.boxhud
java_version=25

# Common
mod_name=BoxHud
mod_author=Boxadactle
mod_id=boxhud
license=GPLv3
credits=
description=BoxHud is a Minecraft mod that adds a suite of powerful and customizable PvP-style HUD widgets, with a focus on performance and customizability.
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

enabled_platforms=fabric,forge,neoforge

minecraft_version=26.1.1
minecraft_version_range=[26, 27)
minecraft_version_range_fabric=>=26

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.3+26.1.1
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.8

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.1.8-beta
neoforge_loader_version_range=[4,)

# BoxLib https://modrinth.com/mod/boxlib#download
boxlib_version=21.0.0
boxlib_version_range=[21,22)
boxlib_version_range_fabric=21.x

# Coordinates Display https://modrinth.com/mod/coordinates-display#download
coordinates_display_version = 20.0.0-snapshot
coordinates_display_version_range=[20.0, 21.0)
coordinates_display_version_range_fabric=20.x
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# publishing to platforms
game_versions = 26.1,26.1.1
project_id_curseforge = 1320027
project_id_modrinth = gjFWUARA
release_type = release
changelog_file = CHANGELOG.md